---
triggers:
- x: 3
  y: 0
  layer: 1
  script: $DWarp
  arguments:
    mapName: Viridian_City
    x: 29
    y: 16
    layer: 1
- x: 4
  y: 0
  layer: 1
  script: $DWarp
  arguments:
    mapName: Viridian_City
    x: 29
    y: 16
    layer: 1