---
triggers:
- x: 18
  y: 0
  layer: 1
  script: $DWarp
  arguments:
    mapName: Route2_South_Forest
    x: 5
    y: 7
    layer: 1
- x: 17
  y: 0
  layer: 1
  script: $DWarp
  arguments:
    mapName: Route2_South_Forest
    x: 5
    y: 7
    layer: 1
- x: 16
  y: 0
  layer: 1
  script: $DWarp
  arguments:
    mapName: Route2_South_Forest
    x: 5
    y: 7
    layer: 1
- x: 15
  y: 0
  layer: 1
  script: $DWarp
  arguments:
    mapName: Route2_South_Forest
    x: 5
    y: 7
    layer: 1
- x: 1
  y: 47
  layer: 1
  script: $Warp
  arguments:
    mapName: Route2_North_Forest
    x: 4
    y: 0
    layer: 1
- x: 2
  y: 47
  layer: 1
  script: $Warp
  arguments:
    mapName: Route2_North_Forest
    x: 4
    y: 0
    layer: 1