---
triggers:
- x: 8
  y: 7
  layer: 1
  script: $Warp
  arguments:
    mapName: Pallet_Town_Red_Home_2
    x: 8
    y: 7
    layer: 0
- x: 3
  y: 0
  layer: 1
  script: $Warp
  arguments:
    mapName: Pallet_Town
    x: 11
    y: 12
    layer: 1
    warpWalk: S
- x: 4
  y: 0
  layer: 1
  script: $Warp
  arguments:
    mapName: Pallet_Town
    x: 11
    y: 12
    layer: 1
    warpWalk: S