---
triggers:
- x: 23
  y: 10
  layer: 1
  script: $Warp
  arguments:
    mapName: Viridian_City_PC
    x: 3
    y: 0
    layer: 1
- x: 29
  y: 16
  layer: 1
  script: $Warp
  arguments:
    mapName: Viridian_City_PM
    x: 3
    y: 0
    layer: 1
- x: 21
  y: 20
  layer: 1
  script: $Warp
  arguments:
    mapName: Viridian_City_School
    x: 2
    y: 0
    layer: 1
- x: 21
  y: 26
  layer: 1
  script: $Warp
  arguments:
    mapName: Viridian_City_House
    x: 2
    y: 0
    layer: 1
- x: 19
  y: 26
  layer: 1
  name: Viridian_City_Roadblock
  script: roadblock