---
triggers:
- x: 5
  y: 0
  layer: 1
  script: $Warp
  arguments:
    mapName: Pallet_Town
    x: 18
    y: 6
    layer: 1
    warpWalk: S
- x: 6
  y: 0
  layer: 1
  script: $Warp
  arguments:
    mapName: Pallet_Town
    x: 18
    y: 6
    layer: 1
    warpWalk: S
- x: 6
  y: 6
  layer: 1
  script: barrier
  name: Pallet_Town_Lab_Barrier
  arguments:
    Side: Right
- x: 5
  y: 6
  layer: 1
  script: barrier
  name: Pallet_Town_Lab_Barrier
  arguments:
    Side: Left