---
triggers:
- x: 3
  y: 0
  layer: 1
  script: $DWarp
  arguments:
    mapName: Pewter_City
    x: 26
    y: 18
    layer: 1
- x: 4
  y: 0
  layer: 1
  script: $DWarp
  arguments:
    mapName: Pewter_City
    x: 26
    y: 18
    layer: 1