---
triggers:
- x: 3
  y: 0
  layer: 1
  script: $Warp
  arguments:
    mapName: Pallet_Town
    x: 19
    y: 12
    layer: 1
    warpWalk: S
- x: 4
  y: 0
  layer: 1
  script: $Warp
  arguments:
    mapName: Pallet_Town
    x: 19
    y: 12
    layer: 1
    warpWalk: S