---
triggers:
- x: 3
  y: 1
  layer: 1
  script: $DWarp
  arguments:
    mapName: Pallet_Town
    x: 19
    y: 12
    layer: 1
- x: 4
  y: 1
  layer: 1
  script: $DWarp
  arguments:
    mapName: Pallet_Town
    x: 19
    y: 12
    layer: 1