---
triggers:
- x: 2
  y: 0
  layer: 1
  script: $DWarp
  arguments:
    mapName: Pewter_City
    x: 32
    y: 22
    layer: 1
- x: 3
  y: 0
  layer: 1
  script: $DWarp
  arguments:
    mapName: Pewter_City
    x: 32
    y: 22
    layer: 1