---
triggers:
- x: 3
  y: 0
  layer: 1
  script: $DWarp
  arguments:
    mapName: Pewter_City
    x: 16
    y: 10
    layer: 1
- x: 4
  y: 0
  layer: 1
  script: $DWarp
  arguments:
    mapName: Pewter_City
    x: 16
    y: 10
    layer: 1